import './globals.css'

export const metadata = {
  title: 'Next 13 Fonts',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <body className='bg-gray-100 dark:bg-gray-800'>{children}</body>
    </html>
  )
}
